# helm/values-production.yaml
# Production-specific configuration with Bitwarden Secrets Manager

# External MariaDB configuration using Bitwarden secrets
dbHost: "mariadb.erpnext.svc.cluster.local"
dbPort: 3306
dbRootUser: "root"
dbExistingSecret: "erpnext-credentials"
dbExistingSecretPasswordKey: "db-root-password"

# Disable built-in MariaDB for production
mariadb:
  enabled: false

# Enable site creation for production using Bitwarden secrets
jobs:
  createSite:
    enabled: true
    siteName: "erpnext.stefenallen.com"
    existingSecret: "erpnext-credentials"
    adminPasswordKey: "admin-password"

# Enable ingress for production
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/upstream-vhost: "erpnext.stefenallen.com"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
  - host: erpnext.stefenallen.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: erpnext-tls
    hosts:
    - erpnext.stefenallen.com

# Production resource allocation
worker:
  replicaCount: 3
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

nginx:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Horizontal Pod Autoscaling
worker:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
